apiVersion: apps/v1
kind: Deployment
metadata:
 name: taskcreationservicedeployment
spec:
 replicas: 1
 selector:
  matchLabels:
   appName: taskcreationservice
 template:
  metadata:
   labels:
    appName: taskcreationservice
  spec:
   containers:
    - name: taskcreationservicepods
      image: gryffindor937/taskcreationservicedeployment:1.0
      imagePullPolicy: Always
      ports:
       - containerPort: 8088
      env:
      - name: spring_profiles_active
        value: cluster
      - name: spring_config_import
        value: configserver:http://tmconfigurationservicelb:8762/config

---

apiVersion: v1
kind: Service
metadata:
 name: taskcreationservicelb
spec:
 selector:
  appName: taskcreationservice
 ports:
  - port: 8088
    targetPort: 8088
 type: LoadBalancer