apiVersion: apps/v1
kind: Deployment
metadata:
 name: tmuserservicedeployment
spec:
 replicas: 1
 selector:
  matchLabels:
   appName: tmuserservice
 template:
  metadata:
   labels:
    appName: tmuserservice
  spec:
   containers:
    - name: tmuserservicepods
      image: gryffindor937/tmuserservicedeployment:1.0
      imagePullPolicy: Always
      ports:
       - containerPort: 8086
      env:
      - name: spring_profiles_active
        value: cluster
      - name: spring_config_import
        value: configserver:http://tmconfigurationservicelb:8762/config

---

apiVersion: v1
kind: Service
metadata:
 name: tmuserservicelb
spec:
 selector:
  appName: tmuserservice
 ports:
  - port: 8086
    targetPort: 8086
 type: LoadBalancer