apiVersion: apps/v1
kind: Deployment
metadata:
 name: apigatewayservicedeployment
spec:
 replicas: 1
 selector:
  matchLabels:
   appName: apigatewayservice
 template:
  metadata:
   labels:
    appName: apigatewayservice
  spec:
   containers:
    - name: apigatewayservicepods
      image: gryffindor937/apigatewayservicedeployment:1.0
      imagePullPolicy: Always
      ports:
       - containerPort: 8087
      env:
      - name: spring_profiles_active
        value: cluster
      - name: spring_config_import
        value: configserver:http://tmconfigurationservicelb:8762/config
---

apiVersion: v1
kind: Service
metadata:
 name: apigatewayservicelb
spec:
 selector:
  appName: apigatewayservice
 ports:
  - port: 8087
    targetPort: 8087
 type: LoadBalancer
