apiVersion: apps/v1
kind: Deployment
metadata:
 name: tasksubmissionservicedeployment
spec:
 replicas: 1
 selector:
  matchLabels:
   appName: tasksubmissionservice
 template:
  metadata:
   labels:
    appName: tasksubmissionservice
  spec:
   containers:
    - name: tasksubmissionservicepods
      image: gryffindor937/tasksubmissionservicedeployment:1.0
      imagePullPolicy: Always
      ports:
       - containerPort: 8089
      env:
      - name: spring_profiles_active
        value: cluster
      - name: spring_config_import
        value: configserver:http://tmconfigurationservicelb.default.svc.cluster.local:8762/config

---

apiVersion: v1
kind: Service
metadata:
 name: tasksubmissionservicelb
spec:
 selector:
  appName: tasksubmissionservice
 ports:
  - port: 8089
    targetPort: 8089
 type: LoadBalancer